/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Controlador_AbstractControlador */

#ifndef _Included_Controlador_AbstractControlador
#define _Included_Controlador_AbstractControlador
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Controlador_AbstractControlador
 * Method:    escribir
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
	JNIEXPORT void JNICALL Java_Controlador_AbstractControlador_escribir(JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
